//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentrosCusto
    {
        public CentrosCusto()
        {
            this.CentrosCusto1 = new HashSet<CentrosCusto>();
            this.ContasPagar = new HashSet<ContasPagar>();
        }
    
        public int CentroCustoID { get; set; }
        public Nullable<int> CentroCustoMestreID { get; set; }
        public string Codigo { get; set; }
        public string Nome { get; set; }
        public string Ajuda { get; set; }
    
        public virtual ICollection<CentrosCusto> CentrosCusto1 { get; set; }
        public virtual CentrosCusto CentrosCusto2 { get; set; }
        public virtual ICollection<ContasPagar> ContasPagar { get; set; }
    }
}
