//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContasPagar
    {
        public ContasPagar()
        {
            this.ContasPagar1 = new HashSet<ContasPagar>();
        }
    
        public int ContaPagarID { get; set; }
        public Nullable<int> ContaPagarMestreID { get; set; }
        public string Descricao { get; set; }
        public System.DateTime CadastroDataHora { get; set; }
        public int CadastroUsuarioID { get; set; }
        public System.DateTime EmissaoData { get; set; }
        public decimal ValorBruto { get; set; }
        public decimal ValorDesconto { get; set; }
        public Nullable<decimal> ValorLiquido { get; set; }
        public int FornecedorID { get; set; }
        public Nullable<int> TipoDocumentoID { get; set; }
        public int ParcelaQuantidade { get; set; }
        public int ParcelaNumero { get; set; }
        public string ParcelaNumeroDocumento { get; set; }
        public string ParcelaCodigoPagamento { get; set; }
        public int ParcelaTipoPagamentoID { get; set; }
        public System.DateTime ParcelaDataVencimento { get; set; }
        public decimal ParcelaValorBruto { get; set; }
        public decimal ParcelaValorDesconto { get; set; }
        public decimal ParcelaValorJuros { get; set; }
        public decimal ParcelaValorMulta { get; set; }
        public Nullable<decimal> ParcelaValorLiquido { get; set; }
        public Nullable<System.DateTime> ParcelaDataPagamento { get; set; }
        public Nullable<decimal> ParcelaValorPago { get; set; }
        public Nullable<int> PlancoContaID { get; set; }
        public Nullable<int> CentroCustoID { get; set; }
    
        public virtual CentrosCusto CentrosCusto { get; set; }
        public virtual ICollection<ContasPagar> ContasPagar1 { get; set; }
        public virtual ContasPagar ContasPagar2 { get; set; }
        public virtual PagamentoTipos PagamentoTipos { get; set; }
        public virtual PlanoContas PlanoContas { get; set; }
    }
}
