//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos
    {
        public Departamentos()
        {
            this.PessoaAssociado = new HashSet<PessoaAssociado>();
        }
    
        public System.Guid DepartamentoID { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<PessoaAssociado> PessoaAssociado { get; set; }
    }
}
