//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DependenteTipos
    {
        public DependenteTipos()
        {
            this.PessoaDependentes = new HashSet<PessoaDependentes>();
        }
    
        public System.Guid DependenteTipoID { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<PessoaDependentes> PessoaDependentes { get; set; }
    }
}
