//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormasPagamentoParcelas
    {
        public int FormaPagamentoParcelaID { get; set; }
        public int FormaPagamentoID { get; set; }
        public string Nome { get; set; }
        public int Dias { get; set; }
        public Nullable<double> PercentualValorTotal { get; set; }
    
        public virtual FormasPagamento FormasPagamento { get; set; }
    }
}
