//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoas
    {
        public Pessoas()
        {
            this.OrdensServico = new HashSet<OrdensServico>();
            this.OrdensServico1 = new HashSet<OrdensServico>();
            this.PessoaContatos = new HashSet<PessoaContatos>();
            this.PessoaDependentes = new HashSet<PessoaDependentes>();
            this.PessoaDocumentos = new HashSet<PessoaDocumentos>();
            this.PessoaEnderecos = new HashSet<PessoaEnderecos>();
            this.PessoasPessoaTipos = new HashSet<PessoasPessoaTipos>();
            this.PessoaTelefones = new HashSet<PessoaTelefones>();
        }
    
        public System.Guid PessoaID { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Observacao { get; set; }
        public string TipoPessoa { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ICollection<OrdensServico> OrdensServico { get; set; }
        public virtual ICollection<OrdensServico> OrdensServico1 { get; set; }
        public virtual PessoaAssociado PessoaAssociado { get; set; }
        public virtual ICollection<PessoaContatos> PessoaContatos { get; set; }
        public virtual ICollection<PessoaDependentes> PessoaDependentes { get; set; }
        public virtual ICollection<PessoaDocumentos> PessoaDocumentos { get; set; }
        public virtual ICollection<PessoaEnderecos> PessoaEnderecos { get; set; }
        public virtual PessoaFisica PessoaFisica { get; set; }
        public virtual PessoaJuridica PessoaJuridica { get; set; }
        public virtual ICollection<PessoasPessoaTipos> PessoasPessoaTipos { get; set; }
        public virtual ICollection<PessoaTelefones> PessoaTelefones { get; set; }
    }
}
