//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaDocumentos
    {
        public System.Guid PessoaDocumentoID { get; set; }
        public System.Guid PessoaID { get; set; }
        public string Nome { get; set; }
        public string Valor { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
    }
}
