//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoContas
    {
        public PlanoContas()
        {
            this.ContasPagar = new HashSet<ContasPagar>();
            this.PlanoContas1 = new HashSet<PlanoContas>();
        }
    
        public int PlanoContaID { get; set; }
        public Nullable<int> PlanoContaMestreID { get; set; }
        public string Codigo { get; set; }
        public string Nome { get; set; }
        public string Ajuda { get; set; }
    
        public virtual ICollection<ContasPagar> ContasPagar { get; set; }
        public virtual ICollection<PlanoContas> PlanoContas1 { get; set; }
        public virtual PlanoContas PlanoContas2 { get; set; }
    }
}
