//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        public System.Guid ProdutoID { get; set; }
        public string CodigoDeBarras { get; set; }
        public string CodigoInterno { get; set; }
        public string Nome { get; set; }
        public Nullable<System.Guid> CompraUnidadeDeMedidaID { get; set; }
        public Nullable<System.Guid> VendaUnidadeDeMedidaID { get; set; }
        public Nullable<decimal> PrecoDeCompra { get; set; }
        public Nullable<decimal> PrecoDeVenda { get; set; }
        public string EstoqueLocal { get; set; }
        public Nullable<double> EstoqueQuantidadeAtual { get; set; }
        public Nullable<double> EstoqueQuantidadeMinima { get; set; }
        public Nullable<double> EstoqueQuantidadeMaxima { get; set; }
        public Nullable<System.Guid> ProdutoGrupoID { get; set; }
    
        public virtual ProdutoGrupos ProdutoGrupos { get; set; }
        public virtual UnidadesDeMedida UnidadesDeMedida { get; set; }
        public virtual UnidadesDeMedida UnidadesDeMedida1 { get; set; }
    }
}
