//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicos
    {
        public Servicos()
        {
            this.OrdensServico = new HashSet<OrdensServico>();
        }
    
        public System.Guid ServicoID { get; set; }
        public string Nome { get; set; }
        public double DescontoParaAssociados { get; set; }
    
        public virtual ICollection<OrdensServico> OrdensServico { get; set; }
    }
}
